### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by danielghost** [oliverfoster/adapt-buildkit-rub#15]
This is likely something we would want to leave as a manual task but it seems like image compression is something we tend to overlook quite often in the initial build phase. Graphics seem to use tinypng to handle this, or at least have heard it mentioned a few times. I assume they use the Photoshop plugin but maybe this is something we could include in the buildkit:
https://tinypng.com/developers
https://tinypng.com/developers/reference/nodejs

**Comment by moloko** [comment]
a really nice idea, but since you only get 500 images per month for free we'd need to consider quite carefully how best to add this. perhaps as an option to run it just on images over a particular file size?

**Comment by oliverfoster** [comment]
https://pngquant.org/

**Comment by oliverfoster** [comment]
https://www.npmjs.com/package/imageoptim

**Comment by oliverfoster** [comment]
there are no native JavaScript image optimization libraries i can find. Might have to think about this one a bit more. having something that can go across operating systems is a must for me but i can be persuaded otherwise.

https://github.com/imagemin/imagemin < looks really promising, but i need to test it out across mac, win and linux.

**Comment by oliverfoster** [comment]
i cannot find a cross platform image minification package and the online ones aren't good with node + api stuffs. closing until this changes.
