### ISSUE TITLE
multiple language folders

### ISSUE THREAD

**Issue by chucklorenz** [oliverfoster/adapt-buildkit-rub#30]
Looking to have the ability to maintain separate language folders: course/en, course/es, course/fr. Error thrown when new language folder and defaultLanguage are both something other than "en".

If I leave the path to course/en but change "_defaultLanguage": “ko”, the course builds, but it won’t load. It is looking for the json files at "course/ko"

**Comment by chucklorenz** [comment]
Appears that "en" is hardcoded in 2 places here: https://github.com/cgkineo/adapt-buildkit-rub/blob/master/buildkit/configurations/actions-stringreplacement.json#L17

**Comment by oliverfoster** [comment]
thanks man

**Comment by oliverfoster** [comment]
done - on rub-develop

**Comment by oliverfoster** [comment]
published - please test

**Comment by chucklorenz** [comment]
Partial success.
Build compiles quickly without error. HTML element includes lang="es". However, page never fully loads. Remains with loading.gif spinning. Dev tools console reports no errors or warnings. (and lang="en" was not changed in the IE conditionals)

What I did:
- uninstalled rub
- installed rub-develop
- changed name of course/en to course/es
- changed config.js "_defaultLanguage": "en" to "es"
- updated my image paths throughout my JSON

**Comment by chucklorenz** [comment]
Because I found that a mismatch between config.js "_defaultLanguage": "en" and the course folder (course/es) caused a compile error ( ENOENT), I tested further.

I tested with two folders in my course root: course/en and course/es.
Build compiles cleanly no matter which value is used with _defaultLanguage. Page never loaded. HTML lang attribute reflected the value used with _defaultLanguage.

**Comment by chucklorenz** [comment]
Ollie, because config.js sits in the course root outside of the language specific files, should _defaultLanguage determine the value of HTML's lang attribute? Doesn't seem so. Seems to me that the lang attribute needs to reflect the language of the pages, so better pulled from the name of the directory (course/es). _defaultLanguage should be used to determine the language of the language picker. Have I got this right?

**Comment by oliverfoster** [comment]
hmm... i'll have another go then, thanks chuck

i think the language picker changes the default language property and the html tag
i'll check

**Comment by oliverfoster** [comment]
it all seems to work fine from here. 
![image](https://cloud.githubusercontent.com/assets/7974663/16564719/fa5f66e2-4200-11e6-82c4-9df0fe23a220.png)
- you can seen the config.json with the _defaultLanguage at fr
- the course/fr folder exists
- i've changed all the en/ references to fr/
- needed to clear the cache to make sure all the json updates in the browser

_defaultLanguage determines which folder to start in and what the html lang attribute will be.
the language picker will change _deaultLanguage and reload the course json from the relevant path, changing the html tag in the process

the conditionals specify the starting html tag only. that they don't change at runtime doesn't matter as they are never used unless needed. if we were in ie7/8/9 those html tags would be used and would be updated by the adapt.loadCourseData function instead of the gt IE 9 one.

which style are you using? the Adapt Learning structure or the Kineo Builds one?

**Comment by chucklorenz** [comment]
Since working with you earlier in the day, I can report that this is now working for me with rub installed (not rub-develop). I completely uninstalled adapt-buildkits, reinstalled it, installed rub, and ran it. Worked for both es and en. It does not work with rub-develop; it can't find "component media" which is the first component encountered in my json.

**Comment by chucklorenz** [comment]
Reminders from a recent gitter conversation:
Chuck Lorenz @chucklorenz 12:47
was ignoring you so you could start your weekend, but…
running 0.0.80
changed course/en > course/es
changed "_defaultLanguage": “en” > “es”
ran ./rub -ds m35t
got the error posted above

Oliver Foster @oliverfoster 12:49
https://github.com/cgkineo/adapt-buildkit-rub/blob/master/buildkit/configurations/actions-stringreplacement.json#L17 < yea, i can see why

**Comment by oliverfoster** [comment]
please check v0.0.81 of master rub @chucklorenz

**Comment by chucklorenz** [comment]
+1
v0.0.81 works for me
Thank you.

**Comment by oliverfoster** [comment]
no worries 👍
